default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: heroku_test_app_development

test:
  <<: *default
  database: heroku_test_app_test

production:
  <<: *default
  database: heroku_test_app_production
  username: heroku_test_app
  password: <%= ENV['HEROKU_TEST_APP_DATABASE_PASSWORD'] %>
